name: CI-CD WAR打包部署

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 配置JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: maven

      - name: Maven打包war
        run: mvn clean package -DskipTests

      - name: 上传war包
        uses: actions/upload-artifact@v3
        with:
          name: demo-war
          path: target/demo.war